version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: mini-games-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: mini_games
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mini-games-network

  redis:
    image: redis:7-alpine
    container_name: mini-games-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mini-games-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  mini-games-network:
    driver: bridge 